### ISSUE TITLE
php56m-fpm start error

### ISSUE THREAD

**Issue by luckytanuki** [KloxoNGCommunity/kloxo#1]
Jul 23 13:34:14 kng.test systemd[1]: Starting The PHP FastCGI Process Manager...
Jul 23 13:34:14 kng.test php56m-fpm[210419]: /opt/php56m/usr/sbin/php-fpm: error while loading shared libraries: libssl.so.1.1: cannot open shared ob>
Jul 23 13:34:14 kng.test systemd[1]: php56m-fpm.service: Main process exited, code=exited, status=127/n/a
Jul 23 13:34:14 kng.test systemd[1]: php56m-fpm.service: Failed with result 'exit-code'.
Jul 23 13:34:14 kng.test systemd[1]: Failed to start The PHP FastCGI Process Manager.

**Comment by kloxoNG** [comment]
fixed in f52a097
