### ISSUE TITLE
PHP74s Install dependencies rpms problem

### ISSUE THREAD

**Issue by luckytanuki** [KloxoNGCommunity/kloxo#11]
- Install dependencies rpms

 Problem 1: cannot install the best candidate for the job
  - nothing provides libmemcached.so.11()(64bit) needed by libyaz-5.32.0-1.el9.remi.x86_64 from kloxo-remi
  - nothing provides libmemcachedutil.so.2()(64bit) needed by libyaz-5.32.0-1.el9.remi.x86_64 from kloxo-remi
 Problem 2: package coreutils-8.32-35.el9.x86_64 from @System conflicts with coreutils-single provided by coreutils-single-8.32-35.el9.x86_64 from baseos
  - cannot install the best candidate for the job
  - conflicting requests
 Problem 3: package libcurl-minimal-7.76.1-29.el9_4.x86_64 from baseos conflicts with libcurl(x86-64) provided by libcurl-7.76.1-29.el9_4.x86_64 from @System
  - cannot install the best candidate for the job

**Comment by luckytanuki** [comment]
Need to try with using --allowerasing flag with yum

**Comment by kloxoNG** [comment]
Fixed in commit c3daf2d
