### ISSUE TITLE
Qmail clamd install / uninstall issues

### ISSUE THREAD

**Issue by djsakisd** [KloxoNGCommunity/kloxo#23]
Hi @kloxoNG 

After i installed virus scanner (clamd) i saw a lot of errors regarding clamd could not find socket.
I then uninstalled but after that qmail logs errors continiously like the above : 
`supervise: fatal: unable to start log/run: file does not exist
supervise: fatal: unable to start clamd/run: file does not exist`

Also i see a lot or `ERROR(exec_checkpassword_argv()@exec.c:356): unable to find executable /var/qmail/bin/smtp_auth: No such file or directory` but i dont know if its related with above errors.

Mail server works fine though despite the errors.

Any idea on how to fix them ?

Thanks !

**Comment by luckytanuki** [comment]
That's caused by daemontool's supervise program not finding the clamd launch files. I haven't tested clamd much as it is a resource hog and slows down servers. How every I will investigate and see if I can fix the issue.

**Comment by djsakisd** [comment]
@luckytanuki  `rm -rf /var/qmail/supervise/clamd` seems to fix the issue from clamd supervise for now.

Do you have any idea what might causing this  ? `ERROR(exec_checkpassword_argv()@exec.c:356): unable to find executable /var/qmail/bin/smtp_auth: No such file or directory` i'm constantly seeing it

**Comment by kloxoNG** [comment]
var/qmail/bin/smtp_auth isn't in the new qmail builds

Looks like the problem is that spamdyke is tryind to use it

in /etc/spamdyke.conf

there's the line `smtp-auth-command=/var/qmail/bin/smtp_auth /var/qmail/bin/true /var/qmail/bin/cmd5checkpw /bin/true`

comment it out and add below it

`smtp-auth-command=/home/vpopmail/bin/vchkpw /bin/true`
so it looks like this

`
#smtp-auth-command=/var/qmail/bin/smtp_auth /var/qmail/bin/true /var/qmail/bin/cmd5checkpw /bin/true
smtp-auth-command=/home/vpopmail/bin/vchkpw /bin/true
`

**Comment by kloxoNG** [comment]
> Hi @kloxoNG
> 
> After i installed virus scanner (clamd) i saw a lot of errors regarding clamd could not find socket. I then uninstalled but after that qmail logs errors continiously like the above : `supervise: fatal: unable to start log/run: file does not exist supervise: fatal: unable to start clamd/run: file does not exist`
> 
I remember this error going back to the original Kloxo-mr . I've tried a few fixes over the years but seems it is still not resolved. I'm going to have to dig deeper.

**Comment by djsakisd** [comment]
> var/qmail/bin/smtp_auth isn't in the new qmail builds
> 
> Looks like the problem is that spamdyke is tryind to use it
> 
> in /etc/spamdyke.conf
> 
> there's the line `smtp-auth-command=/var/qmail/bin/smtp_auth /var/qmail/bin/true /var/qmail/bin/cmd5checkpw /bin/true`
> 
> smtp auth can be done by vpopmail so comment it out and add below it
> 
> `smtp-auth-command=/home/vpopmail/bin/vchkpw /bin/true`
> 
> so it looks like this
> 
> `#smtp-auth-command=/var/qmail/bin/smtp_auth /var/qmail/bin/true /var/qmail/bin/cmd5checkpw /bin/true smtp-auth-command=/home/vpopmail/bin/vchkpw /bin/true`

That seems to fix it , thank you very much,

Closing the issue for now.
